DROP DATABASE IF EXISTS hitw;

CREATE DATABASE hitw;

GO

USE hitw;

-- Create the tables here
CREATE TABLE Person (Id INT IDENTITY PRIMARY KEY, LastName VARCHAR(50), FirstName VARCHAR(50));

CREATE TABLE Project (Id INT IDENTITY PRIMARY KEY, Name VARCHAR(50), PersonId INT,
		CONSTRAINT FK_Person
		FOREIGN KEY (PersonId)
			REFERENCES Person(Id));

CREATE TABLE Theme (Id INT IDENTITY PRIMARY KEY, Name VARCHAR(50));

CREATE TABLE Question (Id INT IDENTITY PRIMARY KEY, Name VARCHAR(50), Data VARCHAR(500), ThemeId INT,
		CONSTRAINT FK_Theme
		FOREIGN KEY (ThemeId)
			REFERENCES Theme(Id));

CREATE TABLE ThemeScore (Id INT IDENTITY PRIMARY KEY, ThemeId INT, ProjectId INT, Score INT,
		CONSTRAINT FK_Project_ThemeScore
		FOREIGN KEY (ProjectId)
			REFERENCES Project(Id),
		CONSTRAINT FK_Theme_ThemeScore
		FOREIGN KEY (ThemeId)
			REFERENCES Theme(Id));

CREATE TABLE Answer (Id INT IDENTITY PRIMARY KEY, Data VARCHAR(500), ThemeScoreId INT, QuestionId INT,
		CONSTRAINT FK_Question
		FOREIGN KEY (QuestionId)
			REFERENCES Question(Id),
		CONSTRAINT FK_ThemeScore
		FOREIGN KEY (ThemeScoreId)
			REFERENCES ThemeScore(Id));

CREATE TABLE Commitment (Id INT IDENTITY PRIMARY KEY, Description VARCHAR(500), TargetDate DATE, ProjectId INT,
		CONSTRAINT FK_Project_Commitment
		FOREIGN KEY (ProjectId)
			REFERENCES Project(Id));

CREATE TABLE Submission (Id INT IDENTITY PRIMARY KEY, Comment VARCHAR(500), Picture VARBINARY(max), CommitmentId INT,
		CONSTRAINT FK_Commitment
		FOREIGN KEY (CommitmentId)
			REFERENCES Commitment(Id));
