// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HITW.Models.Entities
{
    public partial class Answer
    {
        public int Id { get; set; }
        public string Data { get; set; }
        public int? ThemeScoreId { get; set; }
        public int? QuestionId { get; set; }

        public virtual Question Question { get; set; }
        public virtual ThemeScore ThemeScore { get; set; }
    }
}