// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HITW.Models.Entities
{
    public partial class Assessment
    {
        public Assessment()
        {
            CommitmentAssessments = new HashSet<CommitmentAssessment>();
        }

        public int Id { get; set; }
        public int? ProgressAssessment { get; set; }
        public DateTime? CreatedDate { get; set; }
        public int? ProjectAssessmentId { get; set; }
        public bool? IsProducer { get; set; }

        public virtual ProjectAssessment ProjectAssessment { get; set; }
        public virtual ICollection<CommitmentAssessment> CommitmentAssessments { get; set; }
    }
}