// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HITW.Models.Entities
{
    public partial class CapAndNeed
    {
        public int Id { get; set; }
        public string Actor { get; set; }
        public string SupportType { get; set; }
        public string CapTheme { get; set; }
        public string PeopleInvolved { get; set; }
        public string WaysItHelped { get; set; }
        public int? ThemeScoreId { get; set; }

        public virtual ThemeScore ThemeScore { get; set; }
    }
}