// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HITW.Models.Entities
{
    public partial class Commitment
    {
        public Commitment()
        {
            CommitmentAssessments = new HashSet<CommitmentAssessment>();
            Submissions = new HashSet<Submission>();
        }

        public int Id { get; set; }
        public string Description { get; set; }
        public DateTime? TargetDate { get; set; }
        public int? ProjectCommitmentId { get; set; }
        public bool? IsProducer { get; set; }

        public virtual ProjectCommitment ProjectCommitment { get; set; }
        public virtual ICollection<CommitmentAssessment> CommitmentAssessments { get; set; }
        public virtual ICollection<Submission> Submissions { get; set; }
    }
}