// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HITW.Models.Entities
{
    public partial class CommitmentContract
    {
        public int Id { get; set; }
        public byte[] Contract { get; set; }
        public int? ProjectId { get; set; }

        public virtual Project Project { get; set; }
    }
}