// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HITW.Models.Entities
{
    public partial class Commitment
    {
        public Commitment()
        {
            Submission = new HashSet<Submission>();
        }

        public int CommitmentId { get; set; }
        public string Description { get; set; }
        public DateTime? TargetDate { get; set; }
        public int? ProjectId { get; set; }

        public virtual Project Project { get; set; }
        public virtual ICollection<Submission> Submission { get; set; }
    }
}