// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HITW.Models.Entities
{
    public partial class PrioriPosterioriQuestion
    {
        public PrioriPosterioriQuestion()
        {
            PrioriPosterioriValues = new HashSet<PrioriPosterioriValue>();
        }

        public int Id { get; set; }
        public string Question { get; set; }

        public virtual ICollection<PrioriPosterioriValue> PrioriPosterioriValues { get; set; }
    }
}