// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HITW.Models.Entities
{
    public partial class PrioriPosterioriValue
    {
        public int Id { get; set; }
        public string Priori { get; set; }
        public string Posteriori { get; set; }
        public int? ProjectId { get; set; }
        public int? PrioriPosterioriQuestionId { get; set; }

        public virtual PrioriPosterioriQuestion PrioriPosterioriQuestion { get; set; }
        public virtual Project Project { get; set; }
    }
}