// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HITW.Models.Entities
{
    public partial class Project
    {
        public Project()
        {
            Commitment = new HashSet<Commitment>();
            ThemeScore = new HashSet<ThemeScore>();
        }

        public int Id { get; set; }
        public string Name { get; set; }
        public int? PersonId { get; set; }

        public virtual Person Person { get; set; }
        public virtual ICollection<Commitment> Commitment { get; set; }
        public virtual ICollection<ThemeScore> ThemeScore { get; set; }
    }
}