// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HITW.Models.Entities
{
    public partial class ProjectAssessmentLessonLearned
    {
        public int Id { get; set; }
        public string Data { get; set; }
        public bool? IsProducer { get; set; }
        public int? ProjectAssessmentId { get; set; }

        public virtual ProjectAssessment ProjectAssessment { get; set; }
    }
}