// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HITW.Models.Entities
{
    public partial class Question
    {
        public Question()
        {
            Answer = new HashSet<Answer>();
        }

        public int QuestionId { get; set; }
        public string QuestionName { get; set; }
        public string QuestionString { get; set; }
        public int? ThemeId { get; set; }

        public virtual Theme Theme { get; set; }
        public virtual ICollection<Answer> Answer { get; set; }
    }
}