// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HITW.Models.Entities
{
    public partial class Submission
    {
        public int SubmissionId { get; set; }
        public string Comment { get; set; }
        public byte[] Picture { get; set; }
        public int? CommitmentId { get; set; }

        public virtual Commitment Commitment { get; set; }
    }
}