// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HITW.Models.Entities
{
    public partial class TermsOfUseAnswer
    {
        public TermsOfUseAnswer()
        {
            ProjectTermsOfUseAnswers = new HashSet<ProjectTermsOfUseAnswer>();
        }

        public int Id { get; set; }
        public string Data { get; set; }
        public int? TermsOfUseQuestionId { get; set; }

        public virtual TermsOfUseQuestion TermsOfUseQuestion { get; set; }
        public virtual ICollection<ProjectTermsOfUseAnswer> ProjectTermsOfUseAnswers { get; set; }
    }
}