// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HITW.Models.Entities
{
    public partial class TermsOfUseQuestion
    {
        public TermsOfUseQuestion()
        {
            ProjectTermsOfUseAnswers = new HashSet<ProjectTermsOfUseAnswer>();
            TermsOfUseAnswers = new HashSet<TermsOfUseAnswer>();
        }

        public int Id { get; set; }
        public string Data { get; set; }

        public virtual ICollection<ProjectTermsOfUseAnswer> ProjectTermsOfUseAnswers { get; set; }
        public virtual ICollection<TermsOfUseAnswer> TermsOfUseAnswers { get; set; }
    }
}