// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HITW.Models.Entities
{
    public partial class ThemeScore
    {
        public ThemeScore()
        {
            Answer = new HashSet<Answer>();
        }

        public int Id { get; set; }
        public int? ThemeId { get; set; }
        public int? ProjectId { get; set; }
        public int? Score { get; set; }

        public virtual Project Project { get; set; }
        public virtual Theme Theme { get; set; }
        public virtual ICollection<Answer> Answer { get; set; }
    }
}